# Paths do not work here...
#java -jar StateSynth/5GBaseChecker_Statelearner/out/artifacts/5GBaseChecker_Statelearner_jar/5GBaseChecker_Statelearner.jar fgue.properties
java -cp out/artifacts/5GBaseChecker_Statelearner_jar/5GBaseChecker_Statelearner.jar org.example.uelearner.Learner fgue.properties
